set(BUILD_PASOPIA ON CACHE BOOL "Build for TOSHIBA PASOPIA")
set(BUILD_PASOPIA_LCD ON CACHE BOOL "Build for TOSHIBA PASOPIA with LCD")
set(BUILD_PASOPIA7 ON CACHE BOOL "Build for TOSHIBA PASOPIA7")
set(BUILD_PASOPIA7_LCD ON CACHE BOOL "Build for TOSHIBA PASOPIA7 with LCD")
set(BUILD_J3100GT ON CACHE BOOL "Build for Toshiba J-3100GT")
set(BUILD_J3100SL ON CACHE BOOL "Build for Toshiba J-3100SL")

if(BUILD_PASOPIA)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/pasopia.qrc)
	ADD_VM(pasopia emupasopia _PASOPIA)
endif()
if(BUILD_PASOPIA_LCD)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/pasopia_lcd.qrc)
	ADD_VM(pasopia emupasopia_lcd _PASOPIA)
	target_compile_definitions(emupasopia_lcd
		PRIVATE -D_LCD
	)
endif()
if(BUILD_PASOPIA7)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/pasopia7.qrc)
	ADD_VM(pasopia7 emupasopia7 _PASOPIA7)
endif()
if(BUILD_PASOPIA7_LCD)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/pasopia7_lcd.qrc)
	ADD_VM(pasopia7 emupasopia7_lcd _PASOPIA7)
	target_compile_definitions(emupasopia_lcd
		PRIVATE -D_LCD
	)
endif()

if(BUILD_J3100GT)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/j3100gt.qrc)
	ADD_VM(j3100 emuj3100gt _J3100GT)
endif()
if(BUILD_J3100SE)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/j3100se.qrc)
	ADD_VM(j3100 emuj3100se _J3100SE)
endif()
if(BUILD_J3100SL)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/j3100sl.qrc)
	ADD_VM(j3100 emuj3100sl _J3100SL)
endif()
if(BUILD_J3100SS)
	set(RESOURCE ${PROJECT_SOURCE_DIR}/src/qt/common/qrc/j3100ss.qrc)
	ADD_VM(j3100 emuj3100ss _J3100SS)
endif()

