'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
	
	'This class was auto-generated by the StronglyTypedResourceBuilder
	'class via a tool like ResGen or Visual Studio.
	'To add or remove a member, edit your .ResX file then rerun ResGen
	'with the /str option, or rebuild your VS project.
	'''<summary>
	'''  A strongly-typed resource class, for looking up localized strings, etc.
	'''</summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
	 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
	Friend Module Resources
		
		Private resourceMan As Global.System.Resources.ResourceManager
		
		Private resourceCulture As Global.System.Globalization.CultureInfo
		
		'''<summary>
		'''  Returns the cached ResourceManager instance used by this class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("mz80k_kbd.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property
		
		'''<summary>
		'''  Overrides the current thread's CurrentUICulture property for all
		'''  resource lookups using this strongly typed resource class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property
		
		Friend ReadOnly Property _0() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("0", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _2() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _3() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _4() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _5() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _6() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("6", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _7() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("7", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _8() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("8", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property _9() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("9", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property A() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("A", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property B() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("B", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property BREAK() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BREAK", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property C() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("C", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property COMMA() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("COMMA", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property CR() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CR", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property D() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("D", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property DELETE() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DELETE", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property DOWN() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DOWN", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property E() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("E", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property EQUAL() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("EQUAL", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property F() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property G() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("G", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GETSU() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GETSU", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH11() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH11", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH12() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH12", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH13() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH13", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH14() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH14", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH21() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH21", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH22() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH22", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH23() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH23", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH24() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH24", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH31() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH31", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH32", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH33() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH33", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH34() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH34", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH41() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH41", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH42() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH42", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH43() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH43", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH44() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH44", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH51() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH51", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH52() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH52", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH53() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH53", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property GRAPH54() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GRAPH54", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property H() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("H", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property HOME() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("HOME", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property I() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("I", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property J() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("J", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property K() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("K", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property KANA() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("KANA", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property KIN() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("KIN", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property L() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("L", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property M() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("M", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property MINUS() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MINUS", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property N() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("N", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property O() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("O", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property P() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("P", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property PERIOD() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PERIOD", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property Q() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Q", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property R() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("R", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property RIGHT() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RIGHT", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property S() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("S", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SEI() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SEI", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SEMICOLON() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SEMICOLON", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SHIFT() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SHIFT", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SHIFT_PRESSED() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SHIFT_PRESSED", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SLASH() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SLASH", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SPACE() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SPACE", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property SUI() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("SUI", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property T() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("T", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property U() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("U", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property PLUS() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PLUS", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property V() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("V", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property W() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("W", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property X() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("X", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property Y() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Y", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property YEN() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("YEN", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		Friend ReadOnly Property Z() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Z", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
	End Module
End Namespace
