/*
  Towns CD Controller (CDC) definitions.
  Of commands and status.
  (C) 2023.12.19 K.Ohta <whatisthis.sowhat@gmail.com>
 */
#pragma once


namespace FMTOWNS {
	namespace CDC {
	enum {
		COMMAND_SEEK =				0x00,
		COMMAND_READ_MODE2 =		0x01,
		COMMAND_READ_MODE1 =		0x02,
		COMMAND_READ_RAW   =		0x03,
		COMMAND_PLAY_TRACK =		0x04,
		COMMAND_READ_TOC =			0x05,
		COMMAND_READ_CDDA_STATE =	0x06,
		COMMAND_1Fh =				0x1f,
		COMMAND_SET_STATE =			0x80,
		COMMAND_SET_CDDASET =		0x81,
		COMMAND_STOP_CDDA =			0x84,
		COMMAND_PAUSE_CDDA =		0x85,
		COMMAND_86h =				0x86,
		COMMAND_RESUME_CDDA =		0x87,
		COMMAND_9Fh =				0x9f,
	};

// STATUS[0].
// Update from Tsugaru Thanks to Yamakawa-San.
	enum {
		STATUS_ACCEPT			= 0x00,
		STATUS_NOT_ACCEPT		= 0x01,
		STATUS_SEEK_COMPLETED	= 0x04,
		STATUS_READ_DONE		= 0x06,
		STATUS_PLAY_DONE		= 0x07,
		STATUS_DOOR_OPEN_DONE	= 0x09,
		STATUS_DISC_NOT_READY	= 0x10,
		STATUS_DOOR_CLOSE_DONE	= 0x10,
		STATUS_STOP_DONE		= 0x11,
		STATUS_PAUSE_DONE		= 0x12,
		STATUS_RESUME_DONE		= 0x13,
		STATUS_TOC_ADDR			= 0x16,
		STATUS_TOC_DATA			= 0x17,
		STATUS_SUBQ_READ1		= 0x18,
		STATUS_SUBQ_READ2		= 0x19,
		STATUS_SUBQ_READ3		= 0x19,
		STATUS_SUBQ_READ4		= 0x20,
		STATUS_CMD_ABEND		= 0x21,
		STATUS_DATA_PIO			= 0x21,
		STATUS_DATA_DMA			= 0x22,
		STATUS_UNKNOWN			= 0xff,
	};

// status[1] @ status[0] == 00h
// From Tsugaru Thanks to Yamakawa-San.
// Belows are quote from cdrom/cdrom.h for Tsugaru.
//00H 04H xx xx   CDROM BIOS re-shoots command A0H if CDROM returns this code.       (0b00000100)
//00H 08H xx xx   CDROM BIOS re-shoots command A0H if CDROM returns this code.       (0b00001000)
//00H 0DH xx xx   CDROM BIOS Checking (2ndByte)&0x0D and wait for it to be non zero. (0b00001101)
	enum {
		ACCEPT_NOERROR			= 0x00,
		ACCEPT_DATA_TRACK		= 0x01,
		ACCEPT_CDDA_PAUSED		= 0x01,
		ACCEPT_CDDA_PLAYING	= 0x03,
		ACCEPT_04H_FOR_CMD_A0H	= 0x04,
		ACCEPT_08H_FOR_CMD_A0H	= 0x08,
		ACCEPT_MEDIA_CHANGED	= 0x09,
		ACCEPT_WAIT			= 0x0d,
	};

// status[1] @ status[0] == 21h
// From Tsugaru Thanks to Yamakawa-San.
	enum {
		ABEND_PARAMETER_ERROR		= 0x01,
		ABEND_ERR02				= 0x02,
		ABEND_HARDWARE_ERROR_03	= 0x03,
		ABEND_HARDWARE_ERROR_04	= 0x04,
		ABEND_READ_AUDIO_TRACK		= 0x05,
		ABEND_MEDIA_ERROR_06		= 0x06,
		ABEND_DRIVE_NOT_READY		= 0x07,
		ABEND_MEDIA_CHANGED		= 0x08,
		ABEND_HARDWARE_ERROR_09	= 0x09,
		ABEND_ERROR_0C				= 0x0c,
		ABEND_HARDWARE_ERROR_0D	= 0x0d,
		ABEND_RETRY				= 0x0f, // Indicate RETRY ?
	};
	}
}

#ifdef _USE_NAMESPACE_CDC
using FMTOWNS::CDC::COMMAND_SEEK;
using FMTOWNS::CDC::COMMAND_READ_MODE2;
using FMTOWNS::CDC::COMMAND_READ_MODE1;
using FMTOWNS::CDC::COMMAND_READ_RAW;
using FMTOWNS::CDC::COMMAND_PLAY_TRACK;
using FMTOWNS::CDC::COMMAND_READ_TOC;
using FMTOWNS::CDC::COMMAND_READ_CDDA_STATE;
using FMTOWNS::CDC::COMMAND_1Fh;
using FMTOWNS::CDC::COMMAND_SET_STATE;
using FMTOWNS::CDC::COMMAND_SET_CDDASET;
using FMTOWNS::CDC::COMMAND_STOP_CDDA;
using FMTOWNS::CDC::COMMAND_PAUSE_CDDA;
using FMTOWNS::CDC::COMMAND_86h;
using FMTOWNS::CDC::COMMAND_RESUME_CDDA;
using FMTOWNS::CDC::COMMAND_9Fh;

using FMTOWNS::CDC::STATUS_ACCEPT;
using FMTOWNS::CDC::STATUS_NOT_ACCEPT;
using FMTOWNS::CDC::STATUS_SEEK_COMPLETED;
using FMTOWNS::CDC::STATUS_READ_DONE;
using FMTOWNS::CDC::STATUS_PLAY_DONE;
using FMTOWNS::CDC::STATUS_DOOR_OPEN_DONE;
using FMTOWNS::CDC::STATUS_DISC_NOT_READY;
using FMTOWNS::CDC::STATUS_DOOR_CLOSE_DONE;
using FMTOWNS::CDC::STATUS_STOP_DONE;
using FMTOWNS::CDC::STATUS_PAUSE_DONE;
using FMTOWNS::CDC::STATUS_RESUME_DONE;
using FMTOWNS::CDC::STATUS_TOC_ADDR;
using FMTOWNS::CDC::STATUS_TOC_DATA;
using FMTOWNS::CDC::STATUS_SUBQ_READ1;
using FMTOWNS::CDC::STATUS_SUBQ_READ2;
using FMTOWNS::CDC::STATUS_SUBQ_READ3;
using FMTOWNS::CDC::STATUS_SUBQ_READ4;
using FMTOWNS::CDC::STATUS_CMD_ABEND;
using FMTOWNS::CDC::STATUS_DATA_PIO;
using FMTOWNS::CDC::STATUS_DATA_DMA;
using FMTOWNS::CDC::STATUS_UNKNOWN;

using FMTOWNS::CDC::ACCEPT_NOERROR;
using FMTOWNS::CDC::ACCEPT_DATA_TRACK;
using FMTOWNS::CDC::ACCEPT_CDDA_PAUSED;
using FMTOWNS::CDC::ACCEPT_CDDA_PLAYING;
using FMTOWNS::CDC::ACCEPT_04H_FOR_CMD_A0H;
using FMTOWNS::CDC::ACCEPT_08H_FOR_CMD_A0H;
using FMTOWNS::CDC::ACCEPT_MEDIA_CHANGED;
using FMTOWNS::CDC::ACCEPT_WAIT;

using FMTOWNS::CDC::ABEND_PARAMETER_ERROR;
using FMTOWNS::CDC::ABEND_ERR02;
using FMTOWNS::CDC::ABEND_HARDWARE_ERROR_03;
using FMTOWNS::CDC::ABEND_HARDWARE_ERROR_04;
using FMTOWNS::CDC::ABEND_READ_AUDIO_TRACK;
using FMTOWNS::CDC::ABEND_MEDIA_ERROR_06;
using FMTOWNS::CDC::ABEND_DRIVE_NOT_READY;
using FMTOWNS::CDC::ABEND_MEDIA_CHANGED;
using FMTOWNS::CDC::ABEND_HARDWARE_ERROR_09;
using FMTOWNS::CDC::ABEND_ERROR_0C;
using FMTOWNS::CDC::ABEND_HARDWARE_ERROR_0D;
using FMTOWNS::CDC::ABEND_RETRY;
#endif /* _USE_NAMESPACE_CDC */
