# the name of the target operating system
#SET(CMAKE_SYSTEM_NAME Windows)
#SET(CSP_CROSS_BUILD 0)

UNSET(CSP_GCC_TOOLCHAIN_SUFFIX)
if(DEFINED CMAKE_CSP_GCC_VERSION)
  SET(CSP_GCC_TOOLCHAIN_SUFFIX "-${CMAKE_CSP_GCC_VERSION}")
endif()

SET(CMAKE_C_COMPILER gcc${CSP_GCC_TOOLCHAIN_SUFFIX})
SET(CMAKE_CXX_COMPILER g++${CSP_GCC_TOOLCHAIN_SUFFIX})
