# the name of the target operating system
#SET(CMAKE_SYSTEM_NAME Windows)
SET(CSP_CROSS_BUILD 0)

# Choose an appropriate compiler prefix
# which compilers to use for C and C++

UNSET(CSP_LLVM_TOOLCHAIN_SUFFIX)
if(DEFINED CMAKE_CSP_LLVM_VERSION)
   SET(CSP_LLVM_TOOLCHAIN_SUFFIX "-${CMAKE_CSP_LLVM_VERSION}")
endif()
SET(CMAKE_C_COMPILER clang${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_CXX_COMPILER clang++${CSP_LLVM_TOOLCHAIN_SUFFIX})
#SET(CMAKE_RC_COMPILER i686-w64-mingw32-windres)
SET(CMAKE_AR llvm-ar${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_C_COMPILER_AR  llvm-ar${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_CXX_COMPILER_AR  llvm-ar${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_LD  lld${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_LINKER  lld${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_EXE_LINKER lld${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_SHARED_LINKER  lld${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_NM  nm)
SET(CMAKE_RANLIB  llvm-ranlib${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_C_COMPILER_RANLIB  llvm-ranlib${CSP_LLVM_TOOLCHAIN_SUFFIX})
SET(CMAKE_CXX_COMPILER_RANLIB  llvm-ranlib${CSP_LLVM_TOOLCHAIN_SUFFIX})

