SET(CMAKE_SYSTEM_NAME Windows)
SET(XM7_MINGW_PATH /usr/i686-w64-mingw32)
SET(CMAKE_C_COMPILER /usr/bin/i686-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/i686-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER /usr/bin/i686-w64-mingw32-windres)
SET(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> -O coff <FLAGS> <DEFINES> <SOURCE> <OBJECT>")


SET(CMAKE_FIND_ROOT_PATH ${XM7_MINGW_PATH} ${XM7_MINGW_PATH}/target)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_HOST_WIN32 1)
SET(CMAKE_SYSTEM_PROCESSOR "x86")
